name: release

on: push

jobs:
  publish-release:
    runs-on: self-hosted

    container:
      image: arduino/arduino-cli:builder-1
      volumes:
        # cache go dependencies across pipeline's steps
        - $PWD/go:/go

    steps:
      - name: checkout
        uses: actions/checkout@v1
